# Form implementation generated from reading ui file 'w:\projects\qtApps\widgetDemo\ui\main_gui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_widgetDemo(object):
    def setupUi(self, widgetDemo):
        widgetDemo.setObjectName("widgetDemo")
        widgetDemo.resize(400, 300)

        self.retranslateUi(widgetDemo)
        QtCore.QMetaObject.connectSlotsByName(widgetDemo)

    def retranslateUi(self, widgetDemo):
        _translate = QtCore.QCoreApplication.translate
        widgetDemo.setWindowTitle(_translate("widgetDemo", "widgetDemo"))
